<?php

namespace AGORA\Game\SplendorBundle\Repository;

/**
 * SplendorCardRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SplendorCardRepository extends \Doctrine\ORM\EntityRepository
{
}
