<?php

namespace AGORA\Game\SplendorBundle\Repository;

/**
 * SplendorGameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SplendorGameRepository extends \Doctrine\ORM\EntityRepository
{
}
