<?php

namespace AGORA\Game\AugustusBundle\Repository;

/**
 * AugustusBoardRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AugustusBoardRepository extends \Doctrine\ORM\EntityRepository
{
}
