<?php

namespace AGORA\Game\AugustusBundle\Repository;

/**
 * AugustusGameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AugustusGameRepository extends \Doctrine\ORM\EntityRepository
{
}
