<?php

namespace AGORA\Game\AugustusBundle\Repository;

/**
 * AugustusPlayerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AugustusPlayerRepository extends \Doctrine\ORM\EntityRepository
{
}
