<?php

namespace AGORA\Game\MorpionBundle\Repository;

/**
 * MorpionGameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MorpionGameRepository extends \Doctrine\ORM\EntityRepository
{
}
