<?php

namespace AGORA\Game\MorpionBundle\Repository;

/**
 * MorpionPlayerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MorpionPlayerRepository extends \Doctrine\ORM\EntityRepository
{
}
