  develop[m
* [32mdevelop-platform[m
  develop-site[m
  feature/151/revoir_page_jeux_et_description[m
  feature/170/amelioration_page_table_user[m
  feature/181/integration_table_dans_dashboard[m
  feature/22/game_page[m
  feature/28/game_desc_page[m
  feature/31/user_setting_page[m
  feature/61/launchGame[m
  main[m
  old-develop-platform[m
  [31mremotes/origin/FilterBoard[m
  [31mremotes/origin/HEAD[m -> origin/main
  [31mremotes/origin/ImagePathV2[m
  [31mremotes/origin/Test/GameView[m
  [31mremotes/origin/Test/GameView2[m
  [31mremotes/origin/cherry-pick-3b0b0a9c[m
  [31mremotes/origin/dashboard-layout[m
  [31mremotes/origin/develop[m
  [31mremotes/origin/develop-game[m
  [31mremotes/origin/develop-platform[m
  [31mremotes/origin/develop-site[m
  [31mremotes/origin/feature/149/LoginRegisterPageRework[m
  [31mremotes/origin/feature/151/revoir_page_jeux_et_description[m
  [31mremotes/origin/feature/162/others_user_profil_page[m
  [31mremotes/origin/feature/164/Flash-fix[m
  [31mremotes/origin/feature/170/amelioration_page_table_user[m
  [31mremotes/origin/feature/172/servicestests[m
  [31mremotes/origin/feature/179/LatinTextModif[m
  [31mremotes/origin/feature/181/integration_table_dans_dashboard[m
  [31mremotes/origin/feature/22/game_page[m
  [31mremotes/origin/feature/23/registerPage[m
  [31mremotes/origin/feature/25/db-player[m
  [31mremotes/origin/feature/28/game_desc_page[m
  [31mremotes/origin/feature/29/user/register-login[m
  [31mremotes/origin/feature/31/user_setting_page[m
  [31mremotes/origin/feature/35/db-board[m
  [31mremotes/origin/feature/41/page_table[m
  [31mremotes/origin/feature/42/createBoardPage[m
  [31mremotes/origin/feature/43/BoardForm[m
  [31mremotes/origin/feature/57/db-game[m
  [31mremotes/origin/feature/60/joinBoard-1[m
  [31mremotes/origin/feature/60/rejoindreTable[m
  [31mremotes/origin/feature/61/launchGame[m
  [31mremotes/origin/feature/65/search_board[m
  [31mremotes/origin/feature/67/notifications-add[m
  [31mremotes/origin/feature/74/contactList[m
  [31mremotes/origin/feature/84/table_of_user[m
  [31mremotes/origin/feature/89/BoardForm[m
  [31mremotes/origin/feature/AV-20-affichage-de-la-fin-de-la-partie[m
  [31mremotes/origin/feature/Game/6QP/ApplicationTests[m
  [31mremotes/origin/feature/Game/6QP/Controller6QP[m
  [31mremotes/origin/feature/Game/6QP/DepositingCards[m
  [31mremotes/origin/feature/Game/6QP/MercureIntegration[m
  [31mremotes/origin/feature/Game/6QP/MercureNotification[m
  [31mremotes/origin/feature/Game/6QP/PersonalBoard[m
  [31mremotes/origin/feature/Game/6QP/RefactorStaticValues[m
  [31mremotes/origin/feature/Game/6QP/Service6QP[m
  [31mremotes/origin/feature/Game/6QP/SixQPServiceTest[m
  [31mremotes/origin/feature/Game/6QP/SixQPServiceUnitTests[m
  [31mremotes/origin/feature/Game/6QP/SpectatorManagement[m
  [31mremotes/origin/feature/Game/6QP/Test/ControllerTest[m
  [31mremotes/origin/feature/Game/6QP/View6QP[m
  [31mremotes/origin/feature/Game/6QP/fanShapedHand[m
  [31mremotes/origin/feature/Game/6QP/ranking[m
  [31mremotes/origin/feature/Game/ApplicationTests[m
  [31mremotes/origin/feature/Game/CICD[m
  [31mremotes/origin/feature/Game/ChatManagment[m
  [31mremotes/origin/feature/Game/ELKConfiguration[m
  [31mremotes/origin/feature/Game/Entity/PlayerCardSPL[m
  [31mremotes/origin/feature/Game/GLM/ActivateTileRoute[m
  [31mremotes/origin/feature/Game/GLM/ActivationBonus[m
  [31mremotes/origin/feature/Game/GLM/ActivationBonusManagment[m
  [31mremotes/origin/feature/Game/GLM/BrokenChainTreatment[m
  [31mremotes/origin/feature/Game/GLM/BuyFromWarehouse[m
  [31mremotes/origin/feature/Game/GLM/BuyTile[m
  [31mremotes/origin/feature/Game/GLM/BuyTileInteraction[m
  [31mremotes/origin/feature/Game/GLM/CalculatePoints[m
  [31mremotes/origin/feature/Game/GLM/DiceManagement[m
  [31mremotes/origin/feature/Game/GLM/DisplayDrawTileIndicator[m
  [31mremotes/origin/feature/Game/GLM/DisplayPlayerProductionsResources[m
  [31mremotes/origin/feature/Game/GLM/EndOfGameManagement[m
  [31mremotes/origin/feature/Game/GLM/Entity[m
  [31mremotes/origin/feature/Game/GLM/FixDisplayOfGame[m
  [31mremotes/origin/feature/Game/GLM/FixPublish[m
  [31mremotes/origin/feature/Game/GLM/FixReplaceOfTiles[m
  [31mremotes/origin/feature/Game/GLM/FixTestAndPlaceTile[m
  [31mremotes/origin/feature/Game/GLM/FixTestsAndCleanParameters[m
  [31mremotes/origin/feature/Game/GLM/InitializeTemplates[m
  [31mremotes/origin/feature/Game/GLM/LinkedPersonalBoard[m
  [31mremotes/origin/feature/Game/GLM/Migrations[m
  [31mremotes/origin/feature/Game/GLM/PlatformIntegration[m
  [31mremotes/origin/feature/Game/GLM/RoundManagementTests[m
  [31mremotes/origin/feature/Game/GLM/Service/ResourceSales[m
  [31mremotes/origin/feature/Game/GLM/Test/ApplicationTests[m
  [31mremotes/origin/feature/Game/GLM/Test/DTOAndEntityUnityTest[m
  [31mremotes/origin/feature/Game/GLM/TileBonusActivationManagment[m
  [31mremotes/origin/feature/Game/GLM/View/RemoveVillagerNewLeader[m
  [31mremotes/origin/feature/Game/GLM/assets[m
  [31mremotes/origin/feature/Game/GLM/selectionTile[m
  [31mremotes/origin/feature/Game/GLM/testGetAmountOfTileToReplace[m
  [31mremotes/origin/feature/Game/MYR/BirthBonusManagement[m
  [31mremotes/origin/feature/Game/MYR/TestMyrmesEntities[m
  [31mremotes/origin/feature/Game/Myrmes/DataMigration[m
  [31mremotes/origin/feature/Game/PHPStan[m
  [31mremotes/origin/feature/Game/SPL/ActionsSelectedCards[m
  [31mremotes/origin/feature/Game/SPL/AnimationDiscardDevelopmentCards[m
  [31mremotes/origin/feature/Game/SPL/BuyCardTest[m
  [31mremotes/origin/feature/Game/SPL/CardsBoardPurchasability[m
  [31mremotes/origin/feature/Game/SPL/CheckTokenWhenBuyCard[m
  [31mremotes/origin/feature/Game/SPL/Controller/PickToken[m
  [31mremotes/origin/feature/Game/SPL/ControllerTestBuyCard[m
  [31mremotes/origin/feature/Game/SPL/EndScreen[m
  [31mremotes/origin/feature/Game/SPL/FakeData[m
  [31mremotes/origin/feature/Game/SPL/FixTestsForBuyCard[m
  [31mremotes/origin/feature/Game/SPL/MainBoard[m
  [31mremotes/origin/feature/Game/SPL/MainBoardDisplayCards[m
  [31mremotes/origin/feature/Game/SPL/MainBoardTokenDisplay[m
  [31mremotes/origin/feature/Game/SPL/NobleAnimation[m
  [31mremotes/origin/feature/Game/SPL/PersonalBoard[m
  [31mremotes/origin/feature/Game/SPL/Service/ReservationDevelopCard[m
  [31mremotes/origin/feature/Game/SPL/TakeTokenAppTests[m
  [31mremotes/origin/feature/Game/SPL/Tests/FixAfterBuyChange[m
  [31mremotes/origin/feature/Game/SPL/chat[m
  [31mremotes/origin/feature/Game/SPL/ranking[m
  [31mremotes/origin/feature/Game/SPL/serviceTestFix[m
  [31mremotes/origin/feature/Game/ServiceGame[m
  [31mremotes/origin/feature/Game/Splendor/ActionController[m
  [31mremotes/origin/feature/Game/Splendor/FixBugs[m
  [31mremotes/origin/feature/Game/Splendor/Service/TakeToken[m
  [31mremotes/origin/feature/Game/Splendor/TakeNobleTile[m
  [31mremotes/origin/feature/Game/SplendorEntity[m
  [31mremotes/origin/feature/Game/TestMessageService[m
  [31mremotes/origin/feature/Game/Tests/DTO[m
  [31mremotes/origin/feature/Game/displayChat[m
  [31mremotes/origin/feature/Platform/46/userController[m
  [31mremotes/origin/feature/Platform/BoardEntityTest[m
  [31mremotes/origin/feature/UnitTestReserved[m
  [31mremotes/origin/feature/connectFrontBack/displayBoards[m
  [31mremotes/origin/fix/migrationForGames[m
  [31mremotes/origin/main[m
  [31mremotes/origin/old-develop-platform[m
  [31mremotes/origin/preprod[m
