<?php

namespace Container6kZEf9m;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGameSPL3Service extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.jYxDIg3.App\Entity\Game\Splendor\GameSPL' shared service.
     *
     * @return \App\Entity\Game\Splendor\GameSPL
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.jYxDIg3": it needs an instance of "App\\Entity\\Game\\Splendor\\GameSPL" but this type has been excluded in "config/services.yaml".');
    }
}
