<?php

namespace Container6kZEf9m;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGameViewerServiceService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'App\Service\Platform\GameViewerService' shared autowired service.
     *
     * @return \App\Service\Platform\GameViewerService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/Platform/GameViewerService.php';

        return $container->services['App\\Service\\Platform\\GameViewerService'] = new \App\Service\Platform\GameViewerService();
    }
}
