<?php

namespace Container6kZEf9m;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGameManagerServiceService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'App\Service\Game\GameManagerService' shared autowired service.
     *
     * @return \App\Service\Game\GameManagerService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/Game/GameManagerService.php';

        return $container->services['App\\Service\\Game\\GameManagerService'] = new \App\Service\Game\GameManagerService(($container->services['App\\Repository\\Game\\SixQP\\GameSixQPRepository'] ?? $container->load('getGameSixQPRepositoryService')), ($container->services['App\\Repository\\Game\\Splendor\\GameSPLRepository'] ?? $container->load('getGameSPLRepositoryService')), ($container->services['App\\Service\\Game\\SixQP\\SixQPGameManagerService'] ?? $container->load('getSixQPGameManagerServiceService')), ($container->services['App\\Service\\Game\\Splendor\\SPLGameManagerService'] ?? $container->load('getSPLGameManagerServiceService')));
    }
}
