<?php

namespace Container6kZEf9m;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMercure_Hub_Default_MessageHandlerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'mercure.hub.default.message_handler' shared service.
     *
     * @return \Symfony\Component\Mercure\Messenger\UpdateHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/mercure/src/Messenger/UpdateHandler.php';

        return $container->privates['mercure.hub.default.message_handler'] = new \Symfony\Component\Mercure\Messenger\UpdateHandler(($container->privates['mercure.hub.default.traceable'] ?? self::getMercure_Hub_Default_TraceableService($container)));
    }
}
