<?php

namespace Container6kZEf9m;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPublishServiceService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'App\Service\Game\PublishService' shared autowired service.
     *
     * @return \App\Service\Game\PublishService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/Game/PublishService.php';

        return $container->services['App\\Service\\Game\\PublishService'] = new \App\Service\Game\PublishService(($container->privates['mercure.hub.default.traceable'] ?? self::getMercure_Hub_Default_TraceableService($container)));
    }
}
