<?php

namespace Container6kZEf9m;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSPLServiceService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'App\Service\Game\Splendor\SPLService' shared autowired service.
     *
     * @return \App\Service\Game\Splendor\SPLService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/Game/Splendor/SPLService.php';

        return $container->services['App\\Service\\Game\\Splendor\\SPLService'] = new \App\Service\Game\Splendor\SPLService(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->services['App\\Repository\\Game\\Splendor\\PlayerSPLRepository'] ?? $container->load('getPlayerSPLRepositoryService')), ($container->services['App\\Repository\\Game\\Splendor\\TokenSPLRepository'] ?? $container->load('getTokenSPLRepositoryService')), ($container->services['App\\Repository\\Game\\Splendor\\NobleTileSPLRepository'] ?? $container->load('getNobleTileSPLRepositoryService')), ($container->services['App\\Repository\\Game\\Splendor\\DevelopmentCardsSPLRepository'] ?? $container->load('getDevelopmentCardsSPLRepositoryService')));
    }
}
