<?php

namespace Container6kZEf9m;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSixQPControllerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'App\Controller\Game\SixQPController' shared autowired service.
     *
     * @return \App\Controller\Game\SixQPController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/Game/SixQPController.php';

        $container->services['App\\Controller\\Game\\SixQPController'] = $instance = new \App\Controller\Game\SixQPController(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->services['App\\Repository\\Game\\SixQP\\ChosenCardSixQPRepository'] ?? $container->load('getChosenCardSixQPRepositoryService')), ($container->services['App\\Service\\Game\\SixQP\\SixQPService'] ?? $container->load('getSixQPServiceService')), ($container->services['App\\Service\\Game\\LogService'] ?? $container->load('getLogServiceService')), ($container->services['App\\Service\\Game\\PublishService'] ?? $container->load('getPublishServiceService')), ($container->services['App\\Service\\Game\\MessageService'] ?? $container->load('getMessageServiceService')));

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\Game\\SixQPController', $container));

        return $instance;
    }
}
