<?php

namespace Container6kZEf9m;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSearchDataService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'App\Data\SearchData' shared autowired service.
     *
     * @return \App\Data\SearchData
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Data/SearchData.php';

        return $container->services['App\\Data\\SearchData'] = new \App\Data\SearchData();
    }
}
