<?php

namespace Container6kZEf9m;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSixQPServiceService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'App\Service\Game\SixQP\SixQPService' shared autowired service.
     *
     * @return \App\Service\Game\SixQP\SixQPService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/Game/SixQP/SixQPService.php';

        return $container->services['App\\Service\\Game\\SixQP\\SixQPService'] = new \App\Service\Game\SixQP\SixQPService(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->services['App\\Repository\\Game\\SixQP\\CardSixQPRepository'] ?? $container->load('getCardSixQPRepositoryService')), ($container->services['App\\Repository\\Game\\SixQP\\ChosenCardSixQPRepository'] ?? $container->load('getChosenCardSixQPRepositoryService')), ($container->services['App\\Repository\\Game\\SixQP\\PlayerSixQPRepository'] ?? $container->load('getPlayerSixQPRepositoryService')), ($container->services['App\\Service\\Game\\LogService'] ?? $container->load('getLogServiceService')));
    }
}
