<?php

namespace ContainerXK2F6Iq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Lfd0bRYService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Lfd0bRY' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Lfd0bRY'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'gameSPL' => ['privates', '.errored..service_locator.Lfd0bRY.App\\Entity\\Game\\Splendor\\GameSPL', NULL, 'Cannot autowire service ".service_locator.Lfd0bRY": it needs an instance of "App\\Entity\\Game\\Splendor\\GameSPL" but this type has been excluded in "config/services.yaml".'],
        ], [
            'gameSPL' => 'App\\Entity\\Game\\Splendor\\GameSPL',
        ]);
    }
}
