<?php

namespace ContainerXK2F6Iq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JZSENecService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.jZSENec' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.jZSENec'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'game' => ['privates', '.errored..service_locator.jZSENec.App\\Entity\\Game\\SixQP\\GameSixQP', NULL, 'Cannot autowire service ".service_locator.jZSENec": it needs an instance of "App\\Entity\\Game\\SixQP\\GameSixQP" but this type has been excluded in "config/services.yaml".'],
        ], [
            'game' => 'App\\Entity\\Game\\SixQP\\GameSixQP',
        ]);
    }
}
