<?php

namespace ContainerXK2F6Iq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRowSixQPService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.0flv6qU.App\Entity\Game\SixQP\RowSixQP' shared service.
     *
     * @return \App\Entity\Game\SixQP\RowSixQP
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.0flv6qU": it needs an instance of "App\\Entity\\Game\\SixQP\\RowSixQP" but this type has been excluded in "config/services.yaml".');
    }
}
