<?php

namespace ContainerXK2F6Iq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSPLServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\Game\Splendor\SPLService' shared autowired service.
     *
     * @return \App\Service\Game\Splendor\SPLService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'Game'.\DIRECTORY_SEPARATOR.'Splendor'.\DIRECTORY_SEPARATOR.'SPLService.php';

        return $container->privates['App\\Service\\Game\\Splendor\\SPLService'] = new \App\Service\Game\Splendor\SPLService(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['App\\Repository\\Game\\Splendor\\PlayerSPLRepository'] ?? $container->load('getPlayerSPLRepositoryService')), ($container->privates['App\\Repository\\Game\\Splendor\\TokenSPLRepository'] ?? $container->load('getTokenSPLRepositoryService')), ($container->privates['App\\Repository\\Game\\Splendor\\NobleTileSPLRepository'] ?? $container->load('getNobleTileSPLRepositoryService')), ($container->privates['App\\Repository\\Game\\Splendor\\DevelopmentCardsSPLRepository'] ?? $container->load('getDevelopmentCardsSPLRepositoryService')));
    }
}
