<?php

namespace AGORA\Game\RRBundle\Repository;

/**
 * RRGameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RRPlayerRepository extends \Doctrine\ORM\EntityRepository {

}
