<?php

namespace AGORA\Game\SQPBundle\Repository;

/**
 * PlayerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlayerRepository extends \Doctrine\ORM\EntityRepository {
    //Retourne tous les joueurs d'une partie
    public function getAllPlayersFromLobby($gameId) {
        return $this->createQueryBuilder('a')
            ->join('a.gameId', 'g')
            ->join('a.userId', 'u')
            ->where("g.id = :id")
            ->setParameter('id', $gameId)
            ->getQuery()->getResult();

    }

    public function nbPresentPlayersFromLobby($gameId) {
        return $this->createQueryBuilder('a')
            ->select('COUNT(a)')
            ->join('a.gameId', 'g')
            ->join('a.userId', 'u')
            ->where("g.id = :id")
            ->setParameter('id', $gameId)
            ->getQuery()->getResult();
    }
}
