<?php

namespace ContainerZwxhy43;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VffpW4IService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.VffpW4I' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.VffpW4I'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'gameSixQPRepository' => ['privates', 'App\\Repository\\Game\\SixQP\\GameSixQPRepository', 'getGameSixQPRepositoryService', true],
        ], [
            'gameSixQPRepository' => 'App\\Repository\\Game\\SixQP\\GameSixQPRepository',
        ]);
    }
}
