<?php

namespace ContainerZwxhy43;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ENzRjNNService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ENzRjNN' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ENzRjNN'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'gameSixQP' => ['privates', '.errored..service_locator.ENzRjNN.App\\Entity\\Game\\SixQP\\GameSixQP', NULL, 'Cannot autowire service ".service_locator.ENzRjNN": it needs an instance of "App\\Entity\\Game\\SixQP\\GameSixQP" but this type has been excluded in "config/services.yaml".'],
        ], [
            'gameSixQP' => 'App\\Entity\\Game\\SixQP\\GameSixQP',
        ]);
    }
}
