<?php

namespace ContainerZwxhy43;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGameManagerServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\Game\GameManagerService' shared autowired service.
     *
     * @return \App\Service\Game\GameManagerService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'Game'.\DIRECTORY_SEPARATOR.'GameManagerService.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'Game'.\DIRECTORY_SEPARATOR.'AbstractGameManagerService.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'Game'.\DIRECTORY_SEPARATOR.'SixQP'.\DIRECTORY_SEPARATOR.'SixQPGameManagerService.php';

        return $container->privates['App\\Service\\Game\\GameManagerService'] = new \App\Service\Game\GameManagerService(($container->privates['App\\Repository\\Game\\SixQP\\GameSixQPRepository'] ?? $container->load('getGameSixQPRepositoryService')), new \App\Service\Game\SixQP\SixQPGameManagerService(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['App\\Repository\\Game\\SixQP\\PlayerSixQPRepository'] ?? $container->load('getPlayerSixQPRepositoryService')), ($container->privates['App\\Service\\Game\\SixQP\\SixQPService'] ?? $container->load('getSixQPServiceService'))));
    }
}
