<?php

namespace AGORA\Game\AveCesarBundle\Repository;

/**
 * AveCesarPlayerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AveCesarPlayerRepository extends \Doctrine\ORM\EntityRepository
{
}
