<?php

namespace AGORA\Game\AveCesarBundle\Repository;

/**
 * AveCesarGameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AveCesarGameRepository extends \Doctrine\ORM\EntityRepository
{
}
