<?php

namespace AGORA\PlatformBundle\Repository;

/**
 * GameInfoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GameInfoRepository extends \Doctrine\ORM\EntityRepository
{
}
