<?php

namespace AGORA\PlatformBundle\Repository;

/**
 * LeaderboardRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LeaderboardRepository extends \Doctrine\ORM\EntityRepository
{

	public function getLeaderboardWithUser($game = null) {
		
		$qb = $this
		->createQueryBuilder('a')
		->leftJoin('a.userId', 'u')
		->where('a.gameInfoId = :game')
		->setParameter(':game', $game)
		->orderBy('a.elo', 'DESC')
		->addSelect('u');

  		return $qb
    		->getQuery()
    		->getResult();
	}
}


