<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6kZEf9m\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6kZEf9m/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/Container6kZEf9m.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\Container6kZEf9m\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \Container6kZEf9m\App_KernelTestDebugContainer([
    'container.build_hash' => '6kZEf9m',
    'container.build_id' => '8359da7b',
    'container.build_time' => 1710778463,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container6kZEf9m');
