<?php

namespace AGORA\Game\AzulBundle\Repository;


/**
 * PlayerRepository
 * 
 * This class was generated by the Doctrine ORM. Ass your own custom
 * repository methods below.
 */
class AzulPlayerRepository extends \Doctrine\ORM\EntityRepository {
    
}