<?php

namespace AGORA\Game\AzulBundle\Repository;


/**
 * AzulGameRepository
 * 
 * This class was generated by the Doctrine ORM. Ass your own custom
 * repository methods below.
 */
class AzulGameRepository extends \Doctrine\ORM\EntityRepository {

}