<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXK2F6Iq\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXK2F6Iq/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXK2F6Iq.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXK2F6Iq\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXK2F6Iq\App_KernelDevDebugContainer([
    'container.build_hash' => 'XK2F6Iq',
    'container.build_id' => 'fb71f8a1',
    'container.build_time' => 1709302494,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXK2F6Iq');
