<?php

namespace ContainerXmY5Gfg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LJqjyKZService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.lJqjyKZ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.lJqjyKZ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'gameSPLRepository' => ['privates', 'App\\Repository\\Game\\Splendor\\GameSPLRepository', 'getGameSPLRepositoryService', true],
        ], [
            'gameSPLRepository' => 'App\\Repository\\Game\\Splendor\\GameSPLRepository',
        ]);
    }
}
