<?php

namespace ContainerXmY5Gfg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBoardManagerServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\Platform\BoardManagerService' shared autowired service.
     *
     * @return \App\Service\Platform\BoardManagerService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/Platform/BoardManagerService.php';

        return $container->privates['App\\Service\\Platform\\BoardManagerService'] = new \App\Service\Platform\BoardManagerService(($container->privates['App\\Service\\Game\\GameManagerService'] ?? $container->load('getGameManagerServiceService')), ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)));
    }
}
