<?php

namespace ContainerXmY5Gfg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDatabaseToolCollectionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Liip\TestFixturesBundle\Services\DatabaseToolCollection' shared service.
     *
     * @return \Liip\TestFixturesBundle\Services\DatabaseToolCollection
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/liip/test-fixtures-bundle/src/Services/DatabaseToolCollection.php';
        include_once \dirname(__DIR__, 4).'/vendor/liip/test-fixtures-bundle/src/Services/DatabaseTools/AbstractDatabaseTool.php';
        include_once \dirname(__DIR__, 4).'/vendor/liip/test-fixtures-bundle/src/Services/DatabaseTools/AbstractDbalDatabaseTool.php';
        include_once \dirname(__DIR__, 4).'/vendor/liip/test-fixtures-bundle/src/Services/DatabaseTools/ORMDatabaseTool.php';
        include_once \dirname(__DIR__, 4).'/vendor/liip/test-fixtures-bundle/src/Services/DatabaseTools/ORMSqliteDatabaseTool.php';
        include_once \dirname(__DIR__, 4).'/vendor/liip/test-fixtures-bundle/src/Services/DatabaseTools/MongoDBDatabaseTool.php';
        include_once \dirname(__DIR__, 4).'/vendor/liip/test-fixtures-bundle/src/Services/DatabaseTools/PHPCRDatabaseTool.php';
        include_once \dirname(__DIR__, 4).'/vendor/liip/test-fixtures-bundle/src/FixturesLoaderFactoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/liip/test-fixtures-bundle/src/Services/MongoDBFixturesLoaderFactory.php';

        $container->services['Liip\\TestFixturesBundle\\Services\\DatabaseToolCollection'] = $instance = new \Liip\TestFixturesBundle\Services\DatabaseToolCollection($container, NULL);

        $a = ($container->services['Liip\\TestFixturesBundle\\Services\\FixturesLoaderFactory'] ?? $container->load('getFixturesLoaderFactoryService'));

        $instance->add(new \Liip\TestFixturesBundle\Services\DatabaseTools\ORMDatabaseTool($container, $a));
        $instance->add(new \Liip\TestFixturesBundle\Services\DatabaseTools\ORMSqliteDatabaseTool($container, $a));
        $instance->add(new \Liip\TestFixturesBundle\Services\DatabaseTools\MongoDBDatabaseTool($container, ($container->services['Liip\\TestFixturesBundle\\Services\\MongoDBFixturesLoaderFactory'] ??= new \Liip\TestFixturesBundle\Services\MongoDBFixturesLoaderFactory($container, NULL))));
        $instance->add(new \Liip\TestFixturesBundle\Services\DatabaseTools\PHPCRDatabaseTool($container, $a));

        return $instance;
    }
}
