<?php

namespace ContainerXmY5Gfg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGameSixQP3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.ikIzvby.App\Entity\Game\SixQP\GameSixQP' shared service.
     *
     * @return \App\Entity\Game\SixQP\GameSixQP
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.ikIzvby": it needs an instance of "App\\Entity\\Game\\SixQP\\GameSixQP" but this type has been excluded in "config/services.yaml".');
    }
}
