<?php

namespace ContainerXmY5Gfg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMongoDBFixturesLoaderFactoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Liip\TestFixturesBundle\Services\MongoDBFixturesLoaderFactory' shared service.
     *
     * @return \Liip\TestFixturesBundle\Services\MongoDBFixturesLoaderFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/liip/test-fixtures-bundle/src/FixturesLoaderFactoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/liip/test-fixtures-bundle/src/Services/MongoDBFixturesLoaderFactory.php';

        return $container->services['Liip\\TestFixturesBundle\\Services\\MongoDBFixturesLoaderFactory'] = new \Liip\TestFixturesBundle\Services\MongoDBFixturesLoaderFactory($container, NULL);
    }
}
