<?php

namespace ContainerXmY5Gfg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPublisherControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Platform\PublisherController' shared autowired service.
     *
     * @return \App\Controller\Platform\PublisherController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/Platform/PublisherController.php';
        include_once \dirname(__DIR__, 4).'/src/Service/Platform/NotificationService.php';

        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        $container->services['App\\Controller\\Platform\\PublisherController'] = $instance = new \App\Controller\Platform\PublisherController(($container->privates['security.helper'] ?? $container->load('getSecurity_HelperService')), new \App\Service\Platform\NotificationService(($container->privates['mercure.hub.default.traceable'] ?? self::getMercure_Hub_Default_TraceableService($container)), $a), $a);

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\Platform\\PublisherController', $container));

        return $instance;
    }
}
