<?php

namespace AGORA\Game\Puissance4Bundle\Repository;

/**
 * Puissance4PlayerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Puissance4PlayerRepository extends \Doctrine\ORM\EntityRepository
{
}
