<?php

namespace AGORA\Game\Puissance4Bundle\Repository;

/**
 * Puissance4GameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Puissance4GameRepository extends \Doctrine\ORM\EntityRepository
{
}
